services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: achrafaitelquadi/mlops-alzheimer-detection-app:fastapi-latest
    container_name: fastapi_app
    expose:
      - "8000"
    volumes:
      - ./models:/app/models
    depends_on:
      - mlflow
  
  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    image: achrafaitelquadi/mlops-alzheimer-detection-app:mlflow-latest
    container_name: mlflow_ui
    expose:
      - "5000"
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: achrafaitelquadi/mlops-alzheimer-detection-app:nginx-latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - mlflow