services:
  fastapi:
    build:
      context: .
      dockerfile: app/Dockerfile
    image: achrafaitelquadi/fastapi:latest
    container_name: fastapi_app
    expose:
      - "8000"
    volumes:
      - ./models:/app/models
    depends_on:
      - mlflow
      # - prefect
  
  mlflow:
    build:
      context: .
      dockerfile: mlflow/Dockerfile
    image: achrafaitelquadi/mlflow:latest
    container_name: mlflow_ui
    expose:
      - "5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow:5000
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlflow/mlruns --default-artifact-root /mlflow/mlruns

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    image: achrafaitelquadi/nginx-reverse-proxy:latest
    container_name: reverse_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - fastapi
      - mlflow