name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

permissions:
  actions: read
  contents: read

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download model artifacts from CI
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: models
          path: ./models
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_artifacts: true

      - name: Download MLFlow artifacts from CI
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          workflow_conclusion: success
          run_id: ${{ github.event.workflow_run.id }}
          name: mlruns
          path: ./mlruns
          github_token: ${{ secrets.GITHUB_TOKEN }}
          check_artifacts: true

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build and run containers
        run: |
          docker compose up -d --build
          sleep 15  # Attendre que les services démarrent

      - name: Show FastAPI container logs
        run: |
          echo "Checking FastAPI container logs..."
          docker ps
          docker logs $(docker ps -q --filter name=fastapi_app) || echo "Failed to get FastAPI logs"

      - name: Show MLflow container logs
        run: |
          echo "Checking MLflow container logs..."
          docker logs $(docker ps -q --filter name=mlflow_ui) || echo "Failed to get MLflow logs"

      - name: Show Nginx container logs
        run: |
          echo "Checking Nginx container logs..."
          docker logs $(docker ps -q --filter name=reverse_proxy) || echo "Failed to get Nginx logs"

      - name: Inspect FastAPI container filesystem
        run: |
          echo "Current directory in FastAPI container:"
          docker exec fastapi_app pwd || echo "Failed to inspect FastAPI container"
          echo "Contents of /app in FastAPI container:"
          docker exec fastapi_app ls -lah /app || echo "Failed to list /app"
          echo "Contents of /app/models in FastAPI container:"
          docker exec fastapi_app ls -lah /app/models || echo "No models directory"

      - name: Inspect MLflow container filesystem
        run: |
          echo "Current directory in MLflow container:"
          docker exec mlflow_ui pwd || echo "Failed to inspect MLflow container"
          echo "Contents of /mlruns in MLflow container:"
          docker exec mlflow_ui ls -lah /mlruns || echo "No mlruns directory"

      - name: Inspect Nginx container filesystem
        run: |
          echo "Current directory in Nginx container:"
          docker exec reverse_proxy pwd || echo "Failed to inspect Nginx container"
          echo "Contents of /etc/nginx in Nginx container:"
          docker exec reverse_proxy ls -lah /etc/nginx || echo "Failed to list /etc/nginx"

      - name: Test FastAPI internally
        run: |
          echo "Testing FastAPI internally..."
          docker exec fastapi_app curl -s http://localhost:8000/ || echo "FastAPI internal test failed"

      - name: Test MLflow internally
        run: |
          echo "Testing MLflow internally..."
          docker exec mlflow_ui curl -s -I http://localhost:5000/ || echo "MLflow internal test failed"

      - name: Test FastAPI connectivity from Nginx
        run: |
          echo "Testing FastAPI from Nginx container..."
          docker exec reverse_proxy curl -s http://fastapi:8000/ || echo "FastAPI connectivity from Nginx failed"

      - name: Test MLflow connectivity from Nginx
        run: |
          echo "Testing MLflow from Nginx container..."
          docker exec reverse_proxy curl -s -I http://mlflow:5000/ || echo "MLflow connectivity from Nginx failed"

      - name: Download and set up Ngrok
        run: |
          wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-stable-linux-amd64.zip
          unzip ngrok-stable-linux-amd64.zip
          sudo mv ngrok /usr/local/bin
          ngrok config add-authtoken ${{ secrets.NGROK_AUTH_TOKEN }}

      - name: Start Ngrok tunnel for Nginx
        run: |
          nohup ngrok http 80 > ngrok_nginx.log &
          sleep 10

      - name: Show public URL
        run: |
          curl http://localhost:4040/api/tunnels > tunnels.json
          echo "Public URL for Nginx:"
          NGROK_NGINX_URL=$(cat tunnels.json | jq -r '.tunnels[] | select(.proto == "https" and .config.addr == "http://localhost:80") | .public_url')
          echo $NGROK_NGINX_URL

      - name: Keep Ngrok running for testing
        run: |
          echo "Ngrok tunnel is active. Access URL above for manual testing."
          sleep 300  # Garde le tunnel ouvert pendant 5 minutes

      - name: Stop Ngrok
        run: pkill ngrok