name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Download model artifacts
              uses: actions/download-artifact@v3
              with:
                name: models
                path: models

            - name: Download MLFlow artifacts
              uses: actions/download-artifact@v3
              with:
                name: mlruns
                path: mlruns

            - name: Setup Docker
              uses: docker/setup-buildx-action@v2
              
            - name: Build and run with Docker compose
              run : docker-compose up --build