name: Continuous Deployment

on:
  workflow_run:
    workflows: ["Continuous Integration"]
    types:
      - completed

#Permission to download from another workflow
permissions:
  actions: read
  contents: read

jobs:
    deploy:
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3


            - name: Download model artifacts from CI
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: ci.yml
                workflow_conclusion: success
                run_id: ${{ github.event.workflow_run.id }}
                name: models
                path: ./models
                github_token: ${{ secrets.GITHUB_TOKEN }}
                check_artifacts: true
            
            - name: Download MLFlow artifacts from CI
              uses: dawidd6/action-download-artifact@v2
              with:
                workflow: ci.yml
                workflow_conclusion: success
                run_id: ${{ github.event.workflow_run.id }}
                name: mlruns
                path: ./mlruns
                github_token: ${{ secrets.GITHUB_TOKEN }}
                check_artifacts: true

            - name: Setup Docker
              uses: docker/setup-buildx-action@v2
              
            # - name: Build and run with Docker compose
            #   run : docker compose build
            
            # - name: Wait for services to be ready
            #   run: sleep 30
            
            - name: Log in Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            - name: Push images to Docker Hub
              run: |
                  docker compose build

                  docker push achrafaitelquadi/fastapi:latest
                  docker push achrafaitelquadi/mlflow:latest
                  docker push achrafaitelquadi/nginx-reverse-proxy:latest
            
                  docker tag fastapi ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:fastapi-latest
                  docker tag mlflow ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:mlflow-latest
                  docker tag nginx-reverse-proxy ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:nginx-latest
                  
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:fastapi-latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:mlflow-latest
                  docker push ${{ secrets.DOCKER_USERNAME }}/mlops-alzheimer-detection-app:nginx-latest

            - name: Deploy with Docker compose
              run: docker compose up -d
            
            
















            # - name: Log in to Docker Hub
            #   run : echo "{{ secrets.DOCKER_PASSWORD }}" | docker login -u "{{ secrets.DOCKER_USERNAME }}" --password-stdin
            
            # - name: Build all images
            #   run: docker compose build
            
            # - name: Push images to Docker Hub
            #   run: |
            #     docker push achrafaitelquadi/fastapi:latest
            #     docker push achrafaitelquadi/nginx-reverse-proxy:latest
